### ISSUE TITLE
冒昧问一个问题，打扰抱歉

### ISSUE THREAD

**Issue by Awhisper** [evilgix/Evil#1]
我看到您展示了一个训练好的 二代身份证的 mlmodel
特别想问问，哪里能找到这种训练比较好的开放的mlmodel，我特别想找通用文字OCR的mlmodel，想拿来快速处理视频流，tesseract太慢了

**Comment by KevinGong2013** [comment]
你可以看看这里: [Get a core ml model](https://developer.apple.com/documentation/coreml/getting_a_core_ml_model?language=swift)    
一些常用的网络模型都可以转换为我们需要的`mlmodel`

**Comment by Awhisper** [comment]
收到 感谢
